<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tremor</string>
		<string>trickle</string>
	</array>
	<key>name</key>
	<string>Tremor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#line-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(this)\b</string>
					<key>name</key>
					<string>constant.other.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0b[0-1_]*)|(0x[0-9a-fA-F_]*)|([0-9][0-9_]*(\.[0-9][0-9_]*)?((e|E)(\+|-)?[0-9_]+)?))\b</string>
					<key>name</key>
					<string>constant.numeric.tremor</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.tremor</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([_a-z][_a-zA-Z0-9]*)\b(\(|\[)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.tremor</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\.\s*([_a-z][_a-zA-Z0-9]*)\b[^\(\[]</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.tremor</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@\s*([_a-zA-z][_a-zA-Z0-9]*)\s*(\(|\[)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_*[A-Z][_a-zA-Z0-9]*)\b</string>
					<key>name</key>
					<string>entity.name.class.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_*[a-z][_a-zA-Z0-9']*)</string>
					<key>name</key>
					<string></string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>

				<dict>
					<key>match</key>
					<string>\b(select|create|define)\b</string>
					<key>name</key>
					<string>keyword.other.declaration.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(operator|script)\b</string>
					<key>name</key>
					<string>keyword.other.builtin-type.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(from|into|with)\b</string>
					<key>name</key>
					<string>keyword.control.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(event|group|args|window)\b</string>
					<key>name</key>
					<string>keyword.data.tremor</string>
				</dict>


				<dict>
					<key>match</key>
					<string>\b(const|let)\b</string>
					<key>name</key>
					<string>keyword.other.declaration.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(null)\b</string>
					<key>name</key>
					<string>keyword.other.builtin-type.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(emit|drop)\b</string>
					<key>name</key>
					<string>keyword.control.jump.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(match|patch|merge|case|default|insert|update|upsert|erase|move|copy|end|when|of)\b</string>
					<key>name</key>
					<string>keyword.control.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(for)\b</string>
					<key>name</key>
					<string>keyword.control.loop.tremor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|/(?![/*])|%|&lt;&lt;|&gt;&gt;)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(not|and|or|xor|present|absent)\b</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\?|=&gt;)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\||\&amp;|\,|\^)</string>
					<key>name</key>
					<string></string>
				</dict>
			</array>
		</dict>
		<key>line-comments</key>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.hash.tremor</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tremor</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tremor</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.tremor</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:[abfnrtv\\"0]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{6})</string>
							<key>name</key>
							<string>constant.string.escape.tremor</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.tremor</string>
						</dict>
					</array>
				</dict>
    		</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tremor</string>
</dict>
</plist>
