<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>tremor</string>
        <string>trickle</string>
        <string>troy</string>
    </array>
    <key>name</key>
    <string>Tremor</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#expression</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>expression</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#line-comments</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#keywords</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#identifiers</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#strings</string>
                </dict>
            </array>
        </dict>
        <key>constants</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(true|false|null)\b</string>
                    <key>name</key>
                    <string>constant.language.tremor</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b((0b[0-1_]*)|(0x[0-9a-fA-F_]*)|([0-9][0-9_]*(\.[0-9][0-9_]*)?((e|E)(\+|-)?[0-9_]+)?))\b</string>
                    <key>name</key>
                    <string>constant.numeric.tremor</string>
                </dict>
            </array>
        </dict>
        <key>identifiers</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.name.tremor</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\b([_a-z][_a-zA-Z0-9]*)\b(\(|\|)</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.module.tremor</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.separator.tremor</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\b([_a-z][_a-zA-Z0-9]*)\b(\:\:))+</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>object.fields.tremor</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\.\s*([_a-z][_a-zA-Z0-9]*)\b[^\(]</string>
                </dict>
            </array>
        </dict>
        <key>keywords</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(event|state)\b</string>
                    <key>name</key>
                    <!-- using this scope to color these as special -->
                    <string>keyword.other.new.tremor</string>
                </dict>

                <dict>
                    <key>match</key>
                    <string>\b(select|create|define)\b</string>
                    <key>name</key>
                    <string>storage.statement.tremor-query</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(operator|script|pipeline)\b</string>
                    <key>name</key>
                    <string>keyword.control.builtin-type.tremor-query</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(connector|flow|pipeline)\b</string>
                    <key>name</key>
                    <string>keyword.control.builtin-type.tremor-deploy</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(deploy|connect|to)\b</string>
                    <key>name</key>
                    <string>storage.statement.tremor-deploy</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(from|into|with)\b</string>
                    <key>name</key>
                    <string>keyword.control.tremor-query</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(group|by|args|window|stream|tumbling|sliding|where|having)\b</string>
                    <key>name</key>
                    <string>keyword.control.data.tremor-query</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(set|each)\b</string>
                    <key>name</key>
                    <string>keyword.control.grouping.tremor-query</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(emit|drop)\b</string>
                    <key>name</key>
                    <string>storage.jump.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(const|let)\b</string>
                    <key>name</key>
                    <string>keyword.control.declaration.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(for)\b</string>
                    <key>name</key>
                    <string>keyword.control.loop.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(match|of|case|when|default|end)\b</string>
                    <key>name</key>
                    <string>keyword.control.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(patch|insert|upsert|update|erase|move|copy|merge)\b</string>
                    <key>name</key>
                    <string>keyword.control.patch.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(fn|intrinsic|recur)\b</string>
                    <key>name</key>
                    <string>keyword.control.function.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(use|as|mod)\b</string>
                    <key>name</key>
                    <string>keyword.control.modularity.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\-|\+|\*|/(?![/*])|%)</string>
                    <key>name</key>
                    <string>keyword.other.operator.arithmetic.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(&lt;&lt;|(&gt;)?&gt;&gt;)</string>
                    <key>name</key>
                    <string>keyword.other.operator.bitshift.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <!-- space in front of | is to distinguish this operator from extractor delimiter -->
                    <string>( \||\&amp;|\^)</string>
                    <key>name</key>
                    <string>keyword.other.operator.bitwise.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
                    <key>name</key>
                    <string>keyword.other.operator.comparison.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(not|and|or|xor|present|absent)\b</string>
                    <key>name</key>
                    <string>keyword.other.operator.boolean.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\?|=&gt;|`|\$)</string>
                    <key>name</key>
                    <string>keyword.other.operator.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>=</string>
                    <key>name</key>
                    <string>keyword.other.operator.assignment.tremor-script</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\,)</string>
                    <key>name</key>
                    <string></string>
                </dict>

            </array>
        </dict>
        <key>line-comments</key>
        <dict>
            <key>begin</key>
            <string>#</string>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>comment.line.hash.tremor</string>
        </dict>
        <key>strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.tremor</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>"</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.tremor</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.double.tremor</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>\\(?:[abfnrtv\\"0#]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{6})</string>
                            <key>name</key>
                            <string>constant.character.escape</string>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\\.</string>
                            <key>name</key>
                            <string>invalid.illegal.tremor</string>
                        </dict>
                        <dict>
                          <key>include</key>
                          <string>#interpolation</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>interpolation</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>#\{</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.interpolation.begin.tremor</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\}</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.interpolation.end.tremor</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#expression</string>
                      </dict>
                    </array>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.tremor</string>
</dict>
</plist>
