name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.61.0
        profile: minimal
    - uses: Swatinem/rust-cache@v1
    - name: install tremor language server
      uses: actions-rs/cargo@v1
      env:
        RUSTFLAGS: '-C target-cpu=native'
      with:
        command: install
        args: --git https://github.com/tremor-rs/tremor-language-server.git --tag v0.12.0

    # Install node modules
    - name: Dependencies
      run: npm install

    - name: Test
      uses: GabrielBB/xvfb-action@v1.2
      env:
        VSCODE_CLI: 1
      with:
        run: npm run test

    - name: Gramar Test
      run: npm run tmgrammar-test
